### PR TITLE
moving iframe content documents into the 'doc' directory

### PR DESCRIPTION
**Pull request by mikedb66**

### CODE REVIEW

**Comment by lola-masson** [comment]
The images do not show properly -> they are in the /img folder which should probably be moved in the /doc folder, at least for the images that go with the tutorial, otherwise the paths to the images are messed up. Maybe we can have a /img in the mail folder that holds "general" images (logo, etc...) and the /img in the /doc that holds images related to technical doc.

**Comment by mikedb66** [comment]
It looks like all the images for the 'doc' files are in the 'img' folder, while all the images used for the html pages are in 'assets.' Is there an easy way to just move the entire 'img' folder into 'doc'?

**Comment by lola-masson** [comment]
Yes, you can just move the folder on you local machine while you're on your branch, then do the usual add commit push cycle (this might show as "creating a new folder in /doc and deleting the folder /img", instead of showing as "moved"). I think there is as logo remaining in the /img doc, it's proabably from the "styling" side? Or maybe it is just unused

**Comment by mikedb66** [comment]
I did see that file, it's the orange ifm logo with a cast shadow - I don't recall seeing that in use anywhere.

**Comment by mikedb66** [comment]
Tried moving the file using Visual Studio Code, and synched the commit - changes still not being shown on the live commit.

**Comment by mikedb66** [comment]
Got it. Sorry - missed a step.

**Comment by lola-masson** [comment]
The tutorials don't display properly in my browser:
image

I'm not sure what happened, but there is only a tiny piece of the tutorial that appears

**Comment by mikedb66** [comment]
That's really strange. I'm not seeing that behavior - I cleared my cache and it still works fine.

**Comment by lola-masson** [comment]
which browser are you using? I've tried and got this same behavior with Firefox and Chrome. I'm checking if it's something with my local setup.

**Comment by mikedb66** [comment]
Chrome, v. 91.0.4472.101

**Comment by lola-masson** [comment]
Ok that's my bad, works all fine when I display with the live server!

**Comment by lola-masson** [comment]
I still see a display bug for one of the tutorials: the bottom of the frame is cut. Can you reproduce? 
bug_tutorial

**Comment by mikedb66** [comment]
I am seeing the bottom line of that iframe content getting cut off, yes. I'll look into it.

**Review by lola-masson — APPROVED** [review]

**Pull request merged**
