### PR TITLE
Mikedb66 display selected lines of code

### PR DESCRIPTION
**Pull request by mikedb66**
Added display.html to display selected lines of a code file. Added a copy of exposure-times.cpp to use as a test file.

### CODE REVIEW

**Comment by lola-masson** [comment]
Is there any change I break anything if I just move these three documents to another folder ("resources", or "utils", something like that, just to keep things organized)

**Comment by mikedb66** [comment]
Shouldn't be a problem. If you want it to function as-is, just make sure both the .html and the linked .cpp are in the same folder. If you are going to point it at another script, just replace URL in the .get command is adjusted accordingly.

**Comment by lola-masson** [comment]
Alright. 
And just to make sure I get it, what's the difference between display.html and display-select-lines-of-code.html?

**Comment by lola-masson** [comment]
Closing as we are using a different toolset now.

**Pull request closed without merging**
